{% set name = "RadGEEToolbox" %}
{% set version = "1.6.6" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/18/55/2b1039a1c52a9b1734b375765deb7190a0046fa23d477138af5376807ee2/radgeetoolbox-1.6.6.tar.gz
  sha256: 9e646a3c905844adb1cfe2d12d1c130be8dc931cd1d7507fabc92eddbdf48e9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - earthengine-api
    - numpy
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }} 
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
