{% set name = "RadGEEToolbox" %}
{% set version = "1.7.4" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/0d/18/eb1dbc7e5d040874d3fcff677edb6ff186b2c0a2593ef0a37861cf7ead76/radgeetoolbox-1.7.4.tar.gz
  sha256: 926c24671a30df8a6647573e142f9c312628b7e0fdbbff5e766a4918ece23dbc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - earthengine-api
    - numpy
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }} 
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
