{% set name = "RadGEEToolbox" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35b6d4ca67f4187db485a4d7ddf96a6e7a52ddd045ec96d5741bd6130daf980d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - numpy
    - pandas
    - python >=3.6

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Python package simplifying large-scale operations using Google Earth Engine (GEE) for users who utilize Landsat and Sentinel"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
