{% set name = "RadGEEToolbox" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f0e4f172407316c6197186a95fac2c762a57bedd23fcb4467aa76c1a16ba709

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - numpy
    - pandas
    - python >=3.6

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
