{% set name = "RadGEEToolbox" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4d/9b/0163acc57009d78fab5ee6ddb0be52b0d5f6a12dd118344e38cd8e2d2f3c/radgeetoolbox-1.6.1.tar.gz
  sha256: ba051581c34ab5c52bd64b3cab77a37df19adf9fc19f3bb1a2dd07585b193e82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6,<3.12
    - setuptools
    - wheel
  run:
    - earthengine-api
    - numpy
    - pandas
    - python >=3.6,<3.12

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
